### ISSUE TITLE
Dolphin CORE on linux does not start

### ISSUE THREAD

**Issue by externo6** [libretro/dolphin#43]
When using the latest nightly dolphin core the following is observed:
[ERROR] Failed to open libretro core: "/usr/lib/x86_64-linux-gnu/libretro/dolphin_libretro.so"
[ERROR] Error(s): libpng12.so.0: cannot open shared object file: No such file or directory

OS: Ubuntu 18.04, also tested on 16.04 with same results.

Using CORE from: 
https://buildbot.libretro.com/nightly/linux/x86_64/2018-08-21_cores/

Thanks!

**Comment by Heryhelder** [comment]
same problem here. i'm using retroarch 1.7.4 in Fedora 28 via flatpak.

**Comment by i30817** [comment]
This was fixed in the nightly

**Comment by mauriciv** [comment]
I have the same problem, running retroarch 1.7.5 in Fedora 29 via flatpak.

After running retroarch via `flatpak run org.libretro.RetroArch --verbose`, the problem seems to be this line:
`[ERROR] Error(s): libudev.so.1: cannot open shared object file: No such file or directory`

@i30817 what nightly are you referring to? I'm using the dolphin_libretro.so core updated on 2018-10-01 and it still has this problem.

**Comment by i30817** [comment]
I'm referring to the fact the days before i made my comment, there was a commit to bundle libpng, which was  the original problem. Flatpack being broken is sadly not very surprising. Try to do a complete `flatpack upgrade`, that might upgrade the system libs it uses (or might not).

**Comment by emersonnovais** [comment]
I have the same issue on Lubuntu 16.04 and Ubuntu 18.04, both 64 bits, and the problem still persists with updating the core via "Online Updater".
